version: '3.8'

services:
  anatel-integration:
    build: .
    container_name: anatel-spectrum-integration
    restart: unless-stopped
    environment:
      - SPECTRUM_BOARD_URL=${SPECTRUM_BOARD_URL:-http://localhost:3000/api/upload}
      - CRON_SCHEDULE=${CRON_SCHEDULE:-0 * * * *}
      - HTTP_TIMEOUT=${HTTP_TIMEOUT:-30000}
      - LOG_LEVEL=${LOG_LEVEL:-info}
    volumes:
      - anatel_data:/app/anatel_data
    networks:
      - anatel-network
    healthcheck:
      test: ["CMD", "node", "-e", "console.log('Health check')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  anatel_data:
    driver: local

networks:
  anatel-network:
    driver: bridge
